language: generic

# Можно тестировать только на одной платформе (в данном случае выбрано linux, gcc-5)

matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    #- os: osx
      #compiler: clang-3.8
      #env: COMPILER="clang++-3.8" -std=c++11 OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

env:
  global:
    - secure: "hOo2YNC3jPltTQfkMho2XThfX8Xc0sGEn3z4aX2x/Rhdy7KfnqHc8mXFAlCTotZLsYH6jLS/GBTynjUt2h0dNFNswtu/gWxR1piu+gbCzZf7TgCy+0yTKpsq3Ql/fxA7fcgc1ULhgQeUMxqyoxr1HKGR1AuCpJGBEJWk96pSifHKYUKRAoFRdUv15KG+67kkYmFKbiUrDaIIXNudMh7d1kquuDLkBUup4VhtgxxCGVpVXNphM6BxkVPcXfPOw58Y3cUefbYtvF/a/q3Qcqie6KSDE/6rS/ZWqviYoxnh8xwfhdaTCORGYAIX/Ba3KGlHZny29n/adGDb3rQ0dgsyy9rEsEAELc/+UWFkOXU/qcjVriaxX/VX2bTP12DayWj0tqXROCOVdtvWXkHQBmuczW5M3eY9eUpBluEV9GHyPQMv552PsB5daCvmJeNdVN1gU0ZdQuqNr4sX3KA9Mc26ilBbowRauOXFjkk6fJON+UK50IBl4l8RVElCgh7KXQqUPgPtzAQLad6rb92ii9nI52lGpJx1iwroCYC5oO1ZRsWsRd59juM1QFn5zTVvnwRuOUZzGSQ73TjNXCy6/TFgsc0swWsry/AlOjGqHQz+nv/pvtvXm8MCKGMp+yPpVKk4w2CupwppH3hlkLkEXZQVwoTQfXRxLOlKv9RCEntWNWI="
    - secure: "MNSDbeb/5BZlK3LRGoTZ2Z4bOdLfhpp9CgkSv7qTyCsJFAJ5CLYmK+5RugLNsxXMPMOEjII1KG9ryQemhlNhucnKDLzpbpURRqlE98SjjZQoF/PBocG5/JkP+dMA/oyIBo8UAIKmCQnYY4zxKXseJhrnE40zBJphZrcK8Mfj9OIwIbngHVOzWbKsrDim5Yx62eqhv0JN/fnXT6dZEgyMwPOiZUwKjR/HAF0FYYlrxCzhWnj4Pu0xzGrn8X6YsDgVQT5g5t5Gb9ktPjbK1Kh+RJiUFrgsse0WSNsctrWDPihvsqIcZq9C9RtPcyY28gNzCffE0ijWCGpuWInyvIaKnSvG8HSxrD/cGIwMEpEse97yOStw30nnBVtT40tA6I6wNSgPLr1S3t+EKwU9sWLhj1gIZtX2rtbg0ZAUCp3eVD9N5yGIBUggNySsqRbP2a4/sYCBNlyvR3G5x2B0VxvfKEdiGMh6iEznrVfEA0hAqY0IuJUa+Njmf8YkYXt0fqMbSoECZ68XPk5qxdh7UurH/gVZ+clCjomfjn3UToQzcQyy6GT9b4jlkFsNl8RlDRyXQwQdh5dyOo3rHLRk5BhLPIv7Qh8j6wEUnspPGYEwZ9E/fBS1VDoCuuzlZRBzsIjwo6KWFx3EK3tnyFONmGgWBw9UasxBkWeRptTPIp78/Ds="

script:
  - mkdir build && cd build
  - cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib && make
  - ./check -s -r compact
