language: generic

addons:
  apt:
    packages:
      - ccache
      - clang-3.8
      - g++-5
      - cmake
    sources:
      - llvm-toolchain-trusty-3.6
      - ubuntu-toolchain-r-test

# Можно тестировать только на одной платформе (в данном случае выбрано osx, clang-3.8)

#os: linux
#sudo: required
#env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

os: osx
compiler: clang-3.8
env: COMPILER="clang++-3.8" -std=c++11 OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

env:
  global:
    - secure: "Qxv4DzZZ+NAniw9Lxv5FUm9A35b2OEGdiUDMnSr94OLxAWlAvvtZ5cKdnvk+97JIFGDtPryz45JTGyZY7lyiL8wVPXADf9S7pIK4GjzspOlzQOnm4XepM5UO3BIfXVV5Zld7aqLRtlj0bDtvfZzE04FvZD3HNuG8eC+PnQMfrptG3AHpzT96Yxe2Ef733JrnTZ/0WV2uM1slqkDIHm3rp/UAEYE1U5dOcw0a4OhnccPdOHuf/eNLlsQkGhLbN0V/e0sWkL5j/Eoex7jxZnvLGJ+Qyfspn0yBEJgXXFcWcwmrhQprCUFcjbrBoaGtiXkTHaPjXSKU5zyJobAn22K55VoNezK+A+JzTGudEbh5+UqBPcjZHaexwQNxz7+GNo8haZajpuF5K5kE6i3/IoI8OkfI38XFt9Lfcq4KQz1AblcQqO2EQukzHEXr3ivDgmwL08gm2mx4l8oPjM5YxZGw0Y6RZvSxVgDYRCDXi9O3Hf9oJ7+pHXvoisof57seaipbyBIkQIRw69PD/u/aX5Azf9MlHLsXj06pIMzUkFBI9DibLJz+RQUGsz0dfAM2kh3hRHFB1Xg9QnPpQ3aMgoX9Ncl7l+CsX6iVe9w9O56SFEn079Y+Hcd+Mgd+UJCqUU3ApdMz/hWdIHrT39xObBLnRvK3nPS3y3+a6OWgqAjTTTY="
    - secure: "FfjQJdD5wYK9N+aNrSB+hBVVYtVWfbzIjlHi3I5f2MfNZDwnf8JBAh8PlX4U9rZ97sKuYN9jSw2rwb9du2FLSh8EHbXWs4+37Ryc8yUL8xiyq6LBn94OwyOTBZEN7D8y5WJrYfQfwkEorLpXZVUHwLQqz/OJKow7Ww56ETpL4uEc5Gx0Eu9J3wvJo7Q5jRFmlhNbEU/ApXPVcsEbJ8yogerJyRa7eUGtORw/Ugq//JoX+QLrUKwY0tRDHs+Ww7G59in0KZxGczaxM5TwJDEV2QxHTFKaE6iQtiGbUN5+zoWgq3im4xqjfMhIkzl+GGM/kQleIfzc2iJ33R12AV+ubUResXdMipmJLYcKEwCKrpaQKEYbGJvlF+/WezxRH/+reU5rjM3z+NHN7bzAWu4704xO/kVKmh+TOsT6PBdrb6jE7+MbmLmdBJ5heXg54B4ADGCkYCzd7UHaCjOrcp6j90DVKLY717nCMA5wiJc7pLsDs3QP3yRZaKvoZZbEIaYdYFih47u9ZZ9QWrmOCjOorFcRfVuJLnC+8ibTFes7ZgNRZNP6NrB4Z4oqcWgj+pHHKwF2cVrbZZ4lpfXudIO68xJtkoG7cXhhZKjE8mJ59kqFKOp4wGwLq+vyaQOgX9i4CVanqpvqBXqwJurFkStUk2veJR9lXPnftU0gfYI3QoE="

script:
  - mkdir build && cd build
  - cmake .. && make
  #- ./check -s -r compact
