language: generic

# Можно тестировать только на одной платформе (в данном случае выбрано linux, gcc-5)

matrix:
  include:
    #- os: linux
      #sudo: required
      #env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      #addons:
        #apt:
          #packages:
            #- g++-5
            #- cmake
          #sources: &sources
            #- llvm-toolchain-precise
            #- ubuntu-toolchain-r-test
    - os: osx
      compiler: clang-3.8
      env: COMPILER="clang++-3.8" -std=c++11 OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

env:
  global:
    - secure: "hOo2YNC3jPltTQfkMho2XThfX8Xc0sGEn3z4aX2x/Rhdy7KfnqHc8mXFAlCTotZLsYH6jLS/GBTynjUt2h0dNFNswtu/gWxR1piu+gbCzZf7TgCy+0yTKpsq3Ql/fxA7fcgc1ULhgQeUMxqyoxr1HKGR1AuCpJGBEJWk96pSifHKYUKRAoFRdUv15KG+67kkYmFKbiUrDaIIXNudMh7d1kquuDLkBUup4VhtgxxCGVpVXNphM6BxkVPcXfPOw58Y3cUefbYtvF/a/q3Qcqie6KSDE/6rS/ZWqviYoxnh8xwfhdaTCORGYAIX/Ba3KGlHZny29n/adGDb3rQ0dgsyy9rEsEAELc/+UWFkOXU/qcjVriaxX/VX2bTP12DayWj0tqXROCOVdtvWXkHQBmuczW5M3eY9eUpBluEV9GHyPQMv552PsB5daCvmJeNdVN1gU0ZdQuqNr4sX3KA9Mc26ilBbowRauOXFjkk6fJON+UK50IBl4l8RVElCgh7KXQqUPgPtzAQLad6rb92ii9nI52lGpJx1iwroCYC5oO1ZRsWsRd59juM1QFn5zTVvnwRuOUZzGSQ73TjNXCy6/TFgsc0swWsry/AlOjGqHQz+nv/pvtvXm8MCKGMp+yPpVKk4w2CupwppH3hlkLkEXZQVwoTQfXRxLOlKv9RCEntWNWI="
    - secure: "lpPC6lMRJB6XIUVIzEAoh1HbNZZVvb4narYEvt0RD77XnXio8y3AaXy9iDzPXaLPRGCXcFFH+t7fnVJNFpywM/QZ0j4TPvtdGnf8IkkXmnXE8Ai2pE8fzbBFzUPUkyxKTSK4HA0spouHaQjtt5VgsXN6aIu/C6m7u8k+WujYn6cXTyf7wWDe09mLo/8U8DV3a+X0O8NoRhz4j3JwI1dfCwsWQWfTesvTr/iPzfc8wEUYtD3z2+odM+P1Kq9CqI1AYuIsxEhvOTuaWB6vjmmU1Yd8uqt4mz9bLsHtwF4r7T3ASFIVXg6cDCIHRSUMVaNZm2zVeYET5Z9MZd29J35lSXh2fbv18XShjrp9HF14yVjis3xd82GKtKYnwysW5Uw1S4FiJxmI2T1QQgnsgJtLTGY3+1gG98NIeiKJvEfXdCeLM/B9TX9AZHS2m7xwQsKpoygzxYMRNo14cGYmG/WP7D0Xt93VVFXvbo4tP/B5FpCKmdmh5oMFCU1baqhbe0bJ43OXhxk6aWGPJi+10923fekNtHAUvRuWrWAHCoKL1fsDY+VMKliZcO1/W7q2z67gzrThYTFUeKcV3aH7Qei4r+awdERSLOrN/Liq6tSBkoU7Ww0aVwrUHeEGjk8P73wVj0Ou/1n4LFf55dGnhrdujvvm3gZ8hX+9Kmxr7q9wyUk="

script:
  - mkdir build && cd build
  - cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib && make
  - ./check -s -r compact
