language: generic
matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - os: osx
      compiler: clang-3.8
      env: COMPILER="clang++-3.8" -std=c++11 OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
env:
  global:
    - secure: "Qxv4DzZZ+NAniw9Lxv5FUm9A35b2OEGdiUDMnSr94OLxAWlAvvtZ5cKdnvk+97JIFGDtPryz45JTGyZY7lyiL8wVPXADf9S7pIK4GjzspOlzQOnm4XepM5UO3BIfXVV5Zld7aqLRtlj0bDtvfZzE04FvZD3HNuG8eC+PnQMfrptG3AHpzT96Yxe2Ef733JrnTZ/0WV2uM1slqkDIHm3rp/UAEYE1U5dOcw0a4OhnccPdOHuf/eNLlsQkGhLbN0V/e0sWkL5j/Eoex7jxZnvLGJ+Qyfspn0yBEJgXXFcWcwmrhQprCUFcjbrBoaGtiXkTHaPjXSKU5zyJobAn22K55VoNezK+A+JzTGudEbh5+UqBPcjZHaexwQNxz7+GNo8haZajpuF5K5kE6i3/IoI8OkfI38XFt9Lfcq4KQz1AblcQqO2EQukzHEXr3ivDgmwL08gm2mx4l8oPjM5YxZGw0Y6RZvSxVgDYRCDXi9O3Hf9oJ7+pHXvoisof57seaipbyBIkQIRw69PD/u/aX5Azf9MlHLsXj06pIMzUkFBI9DibLJz+RQUGsz0dfAM2kh3hRHFB1Xg9QnPpQ3aMgoX9Ncl7l+CsX6iVe9w9O56SFEn079Y+Hcd+Mgd+UJCqUU3ApdMz/hWdIHrT39xObBLnRvK3nPS3y3+a6OWgqAjTTTY="
    - secure: "bssheTBbrSoepjVEu/hvDWo2OHfep4/3lDOxv6bZ9Nb1Y4iio8Kqy492s/ad0pzjQtSXVQBdzMq283eYj+eazKpCmq5I325Wx36UXNy1gCO/axKOu+RxlLwdd+pK0kPZk4A0sZ/NWPbcVs3RTFgdLHqhK3WZSV4oE3NVkB0hrBuiHoRkfwDhcW9cf/SzjP/YoVxCNEhyLB5ocqaScuZvUli6mA89IY7H/sPC2tyOczO3UOMi2GZhInPpgA+ObvxaedDbBxgLGOrFxgkmPQiH88TfpHdGtesNEn4SkcrSorJJbuXKcgEkBUsf+S7qoxhvBW5Xo9fcqjs2/xIMc3lRUgUuKrOeL93SJ2DIWkxtfW+qGvzkIOajDpagL1SaQ8Itx8mZW3IqX8L7d6sVagOJxDgHM/9VPw6YbosOWUDxNMKnEswSgzqDAFE1UbT1iCuv7uIcTNQ0uqX/94Fcx7n76rqg65pfakediUcuQC3nXG09UK+bN9qLAW3fnEDihboQg6tam8HGoFo7tAC43Nv5MDKMpOiyyvZ5TdhXvTCXcDemasDyGU8W88W/1kxvcCcKsM8BO8SsXzhT3o640suQiD7z142EhV9oJ6pNmBd0xzSwtkFDJv8C6UyL3YPNJ7VgVUIr0tzvPN8lnxBGwcGsTkkKx51OVdqZMcQaBGisIDA="
script:
  - mkdir build && cd build
  - cmake .. && make
  - ./check -s -r compact