language: generic

# Можно тестировать только на одной платформе (в данном случае выбрано osx, clang-3.8)

matrix:
  include:
    #- os: linux
      #sudo: required
      #env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      #addons:
        #apt:
          #packages:
            #- g++-5
            #- cmake
          #sources: &sources
            #- llvm-toolchain-precise
            #- ubuntu-toolchain-r-test
    - os: osx
      compiler: clang-3.8
      env: COMPILER="clang++-3.8" -std=c++11

env:
  global:
    - secure: "Qxv4DzZZ+NAniw9Lxv5FUm9A35b2OEGdiUDMnSr94OLxAWlAvvtZ5cKdnvk+97JIFGDtPryz45JTGyZY7lyiL8wVPXADf9S7pIK4GjzspOlzQOnm4XepM5UO3BIfXVV5Zld7aqLRtlj0bDtvfZzE04FvZD3HNuG8eC+PnQMfrptG3AHpzT96Yxe2Ef733JrnTZ/0WV2uM1slqkDIHm3rp/UAEYE1U5dOcw0a4OhnccPdOHuf/eNLlsQkGhLbN0V/e0sWkL5j/Eoex7jxZnvLGJ+Qyfspn0yBEJgXXFcWcwmrhQprCUFcjbrBoaGtiXkTHaPjXSKU5zyJobAn22K55VoNezK+A+JzTGudEbh5+UqBPcjZHaexwQNxz7+GNo8haZajpuF5K5kE6i3/IoI8OkfI38XFt9Lfcq4KQz1AblcQqO2EQukzHEXr3ivDgmwL08gm2mx4l8oPjM5YxZGw0Y6RZvSxVgDYRCDXi9O3Hf9oJ7+pHXvoisof57seaipbyBIkQIRw69PD/u/aX5Azf9MlHLsXj06pIMzUkFBI9DibLJz+RQUGsz0dfAM2kh3hRHFB1Xg9QnPpQ3aMgoX9Ncl7l+CsX6iVe9w9O56SFEn079Y+Hcd+Mgd+UJCqUU3ApdMz/hWdIHrT39xObBLnRvK3nPS3y3+a6OWgqAjTTTY="
    - secure: "Zzuz5jBZsn/1yYLKNn0SQKV27goeWfVSPIgAZH9ZJikf10jMRhIQxz0nFITKeI65cWHedMIT+sTg3lMWCxb0AkEwd/Ah1jdMSrdRuWmsa6JHM9CnGIDVRVb7PtnoGQQUMPQPpYF+/YcS5DhcNftv01Xb26ylog7UYavqpxTbv+j139fjsUr0OwcPKVgFRAiHUWlMBS23leMuKXWpQfjruLGMReFArjWCERn4qTqqkE5SidUNjPgMklpuXUoaadRuYtzyEgjDUi8uQxRrpEfeamnYEBk2pwBGEKl2aagTce5GegNff6bkwO4rfYMkoB6A0lCw/pV0bCMK4g002bkavG0kD/PMfT+K5dflerP1c1yZf+wbzV4hCrJyM/ennrLmcOdCzcdleIGJZ8pClWFXUJQ80kirIdB28jLMmY03Ptgo5eqEM9stZWVL5PhtiIBudqpTloFLO8ryj6+EEU2dxMrxHx2/7y+/dG1cMeAufZrvcTfDVxcIB2RAqiIj1rNka1EMRRY3sSwzanokFUIZIYHbLsnooTedpd+ZGjpdEdATxKBk/f4jNPRlPOf2bLykk4MOoxFhFLc2kXTercTQ8jN3pvQoA0uYsKxXIaCZWZZ2Em4Hm4UnnaY+4m1kNzzGlDlK6scD4p3TRsFzwHZKh1CsBQd3xIftMJAJU6RNj28="

script:
  - mkdir build && cd build
  - cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib && make
  - ./check -s -r compact
